In [1]:
import numpy as np

# -----------------------------
# Array Creation
# -----------------------------
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

arr2 = np.arange(1, 11)          # 1 to 10
arr3 = np.linspace(0, 1, 5)      # 0 to 1 equally spaced
print("Arange:", arr2)
print("Linspace:", arr3)

Array: [1 2 3 4 5]
Arange: [ 1  2  3  4  5  6  7  8  9 10]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [2]:

# -----------------------------
# Element-wise Operations
# -----------------------------
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


In [3]:

# -----------------------------
# Aggregations
# -----------------------------
print("\nSum:", a.sum())
print("Mean:", a.mean())
print("Standard Deviation:", a.std())
print("Max:", a.max(), "at index", a.argmax())


Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Max: 40 at index 3


In [8]:

# -----------------------------
# Mathematical Functions
# -----------------------------
x = np.array([1, 2, 3])
print("\nSqrt:", np.sqrt(x))
print("Exp:", np.exp(x))
print("Log:", np.log(x))


Sqrt: [1.         1.41421356 1.73205081]
Exp: [ 2.71828183  7.3890561  20.08553692]
Log: [0.         0.69314718 1.09861229]


In [9]:
# -----------------------------
# Mini Project – Student Marks
# -----------------------------
marks = np.random.randint(50, 101, size=10)
print("\nStudent Marks:", marks)
print("Average Marks:", marks.mean())
print("Highest Marks:", marks.max())
print("Lowest Marks:", marks.min())


Student Marks: [67 61 61 72 90 65 97 86 85 60]
Average Marks: 74.4
Highest Marks: 97
Lowest Marks: 60


In [10]:

# -----------------------------
# Mini Project – Matrix Operations
# -----------------------------
matrix = np.array([[1, 2], [3, 4]])
print("\nMatrix:\n", matrix)
print("Transpose:\n", matrix.T)
print("Matrix Multiplication:\n", np.dot(matrix, matrix))


Matrix:
 [[1 2]
 [3 4]]
Transpose:
 [[1 3]
 [2 4]]
Matrix Multiplication:
 [[ 7 10]
 [15 22]]


In [11]:

# -----------------------------
# Mini Project – Dice Roll Simulation
# -----------------------------
dice_rolls = np.random.randint(1, 7, size=20)
print("\nDice Rolls:", dice_rolls)
print("Frequency of Each Face:", np.bincount(dice_rolls)[1:])


Dice Rolls: [1 5 1 5 6 1 5 1 5 3 3 1 6 5 6 5 3 5 1 5]
Frequency of Each Face: [6 0 3 0 8 3]
