In [1]:
import numpy as np

# -----------------------------
# 1. Slicing
# -----------------------------
arr = np.arange(1, 11)   # 1 to 10
print("Original Array:", arr)

print("Slice [2:6]:", arr[2:6])       # elements 3 to 6
print("Every 2nd element:", arr[::2]) # step slicing
print("Reverse:", arr[::-1])          # reverse array

matrix = np.arange(1, 13).reshape(3, 4)
print("\nMatrix:\n", matrix)
print("First 2 rows, col 1-3:\n", matrix[0:2, 1:3])
print("Last row:", matrix[-1])

Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Slice [2:6]: [3 4 5 6]
Every 2nd element: [1 3 5 7 9]
Reverse: [10  9  8  7  6  5  4  3  2  1]

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First 2 rows, col 1-3:
 [[2 3]
 [6 7]]
Last row: [ 9 10 11 12]


In [2]:
# -----------------------------
# 2. Broadcasting
# -----------------------------
data = np.array([[10, 20, 30], [40, 50, 60]])
print("\nData:\n", data)

print("Add scalar 5:\n", data + 5)
print("Multiply by [1, 2, 3]:\n", data * np.array([1, 2, 3]))


Data:
 [[10 20 30]
 [40 50 60]]
Add scalar 5:
 [[15 25 35]
 [45 55 65]]
Multiply by [1, 2, 3]:
 [[ 10  40  90]
 [ 40 100 180]]


In [3]:
# -----------------------------
# 3. Statistics
# -----------------------------
stats_arr = np.random.randint(50, 101, size=15)  # marks dataset
print("\nMarks:", stats_arr)

print("Mean:", np.mean(stats_arr))
print("Median:", np.median(stats_arr))
print("Standard Deviation:", np.std(stats_arr))
print("Variance:", np.var(stats_arr))
print("90th Percentile:", np.percentile(stats_arr, 90))
print("Max:", np.max(stats_arr), "at index", np.argmax(stats_arr))
print("Min:", np.min(stats_arr), "at index", np.argmin(stats_arr))



Marks: [79 57 58 87 65 84 82 75 53 56 75 90 78 93 88]
Mean: 74.66666666666667
Median: 78.0
Standard Deviation: 13.097921802925667
Variance: 171.55555555555554
90th Percentile: 89.2
Max: 93 at index 13
Min: 53 at index 8
